title: jekyll-asset-map
email: kalt.steven+jekyll-asset-map@gmail.com
github_username:  SKalt
source: site-src
description: Use hashed assets from webpack/rollup/parcel/another asset wrangler
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  api:
    order:
      - path.md
      - error.md
      - script.md
      - stylesheet.md
      - integrity.md
      - chunks_js.md
      - chunks_css.md
# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
