version: "3.4"

x-abstract:
  # abstract anchorst to be refernced later
  volumes: &volumes
    src: &src_volume .:/srv/jekyll:cached
    bundle: &bundle_volume bundle:/usr/local/bundle
    node_modules: &node_modules_volume node_modules:/node_modules

services:
  jekyll:
    image: jekyll/jekyll:3.8
    volumes:
      - *src_volume
      - *bundle_volume
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_ENV: production
    command: ["jekyll", "serve", "--livereload", "--incremental"]
  # webpack:
  #   image: node:12.9.0-alpine
  #   volumes:
  #     - *src_volume
  #     - *node_modules_volume
  # TODO: a rollup service
  # TODO: a parcel service
  # TODO: a gulp service

volumes:
  node_modules:
  bundle:
